version: "2"
volumes:
  balena-data:
services:
  exporter:
    build: ./node
    ports:
      - "9100:9100"
    privileged: true

  prometheus:
    build: ./prometheus
    network_mode: "host"
    ports:
      - "9090:9090"
    volumes:
      - "balena-data:/data"

  grafana:
    restart: always
    build: ./grafana
    ports:
      - "80:3000"
    volumes:
      - "balena-data:/data"
